### ISSUE TITLE
invalid action "bash" in jbuild

### ISSUE THREAD

**Issue by yixing-liu** [janestreet/ppx_ast#1]
`me@ubuntu:~/OCaml/ppx_ast$ make install`

`jbuilder install `
`File "src/jbuild", line 29, characters 11-62:`
`Error: invalid action, expected one of:`
`  (run <prog> <args)`
`  (chdir <dir> <action>)`
`  (setenv <var> <value> <action>)`

`make: *** [install] Error 1`

and line 29 is  (action  (bash "( echo \"open Import\"; cat ${<}; ) > ${@}"))))

The current version of jbuilder is 0.1.alpha1 and this is the newest public version.

**Comment by ghost** [comment]
you need the latest development version of jbuilder. We'll release a beta1 of jbuilder with a stable jbuild format, but until the format is unstable

**Comment by yixing-liu** [comment]
Could you please provide an alternative way to compile ppx_ast into a module/library? As a rookie, I would be very grateful if you can tell me the ocamlbuild coommand directly.

**Comment by ghost** [comment]
I'm not sure there is a simple way to build it with ocamlbuild, can you try adding our development opam repository?

```
opam repo add janestreet https://github.com/janestreet/opam-repository.git
```

Then you'll be able to do: `opam install ppx_ast`

**Comment by vbgl** [comment]
I try to install `ppx_ast` on a system in which there is no file `/bin/bash`, and it indeed fails.

Do you really need bash to run `echo` and `cat`?

NB: I could successfully install `ppx_ast` by changing `bash` actions into `system` actions in `src/jbuild`.

**Comment by ghost** [comment]
@vbgl the hard-coded `/bin/bash` was removed in the development version of jbuilder, I'll do another release soon (https://github.com/janestreet/jbuilder/pull/36).  This particular action could easily be replaced by the action DSL indeed. Inside Jane Street we use mostly `bash` for actions and the DSL is much more limited, so I have only converted a few packages to be bash free

**Comment by ghost** [comment]
I submitted a minor release of ppx_ast that doesn't use bash: https://github.com/ocaml/opam-repository/pull/8844
