### ISSUE TITLE
ppx_ast requirement of ocaml-version >= "4.06.0" in opam

### ISSUE THREAD

**Issue by ghost** [janestreet/ppx_ast#4]
The new ppx_ast v0.9.2 in opam requires at least 4.06.0 compiler, and this version is part of ppx_driver v0.9.2, ppx_driver v0.9.2 is part of core v0.9.2. Would it be possible to have the minimum version of compiler 4.05.0 instead of 4.06.0? It was recently relaxed from 4.06.0 to 4.05.0 in sexplib [(https://github.com/janestreet/sexplib/issues/32).](https://github.com/janestreet/sexplib/issues/32)

**Comment by avsm** [comment]
There shouldn't be anything in ppx_ast.0.9.2 aside from OCaml 4.06.0 compatibility -- it's fairly normal to issue point releases of the ppx libraries for a new OCaml version, with major versions reserved for feature improvements.

**Comment by lpw25** [comment]
It looks like `ppx_core` is incorrectly depending on `ppx_ast >= 0.9.2` which is causing people problems.

**Comment by avsm** [comment]
cc @trefis

**Comment by ghost** [comment]
Thanks.
